### ISSUE TITLE
Erreur à la création du container

### ISSUE THREAD

**Issue by Liliputech** [sillydebs/plb-docker#1]
erreur lorsque j'essaye de suivre la procédure indiquée : 
`
Could not open input file: composer-setup.php
ERROR: Service 'php' failed to build : The command '/bin/sh -c php composer-setup.php' returned a non-zero code: 1
`

**Comment by Liliputech** [comment]
C'est dû à l'installeur de composer qui a été modifié.
Après avoir retiré le controle du checksum ça fonctionne.

**Comment by sillydebs** [comment]
Ok, je reteste sur ma machine et j'apporte le correctif. Merci
